# Generated by Django 4.2.2 on 2023-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='enlisted',
            field=models.ManyToManyField(blank=True, to='services.employee'),
        ),
    ]
