# Generated by Django 4.2.2 on 2023-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_enlisted_alter_service_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='address',
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='media/service_images/default.jpg', upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='service',
            name='enlisted',
            field=models.ManyToManyField(blank=True, to='services.employee'),
        ),
    ]
