# Generated by Django 4.2.2 on 2023-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(),
        ),
    ]
