# Generated by Django 4.2.2 on 2023-07-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='chosen_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_services', to='services.employee'),
        ),
        migrations.AlterField(
            model_name='service',
            name='enlisted',
            field=models.ManyToManyField(blank=True, related_name='enlisted_services', to='services.employee'),
        ),
    ]
